### ISSUE TITLE
Odevzdaný úkol

### ISSUE THREAD

**Issue by BarbVrat** [BarbVrat/kurz_python_2024#2]
Ahoj, 
do repozitáře jsem nahrála druhý úkol:) Je teda rozdělený na dvě části. Nevím, jestli to tak bylo myšleno, ale dávalo mi to tak smysl.
Pěkný zbytek víkendu
Bára

**Comment by evgeniyako-edu** [comment]
Moc hezký program, všechno v pořádku ;)
